[project]
name = "taller3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "mlflow>=3.3.2",
    "pip>=25.2",
]
